name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Test scenario tags"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ github.event.inputs.name }}:$(date +%s)
